import Head from 'next/head'
import { FC, PropsWithChildren } from 'react'
import styles from '../../scss/MainTheme.module.scss'
import Footer from '../Footer'
import Navbar from '../Navbar'

const MainTheme: FC<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap'
          rel='stylesheet'
        />
      </Head>
      <div className={styles.wrapper}>
        <Navbar />
        <main className={styles.content}>{children}</main>
        <Footer />
      </div>
    </>
  )
}

export default MainTheme
